CREATE TABLE IF NOT EXISTS `banner` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `banner_id` VARCHAR(64) NOT NULL UNIQUE COMMENT '轮播图ID',
  `title` VARCHAR(100) NOT NULL COMMENT '标题',
  `image_url` VARCHAR(500) NOT NULL COMMENT '图片URL',
  `sort_order` INT DEFAULT 0 COMMENT '排序（越小越靠前）',
  `jump_type` VARCHAR(20) NOT NULL DEFAULT 'NONE' COMMENT '跳转类型: NONE/PRODUCT/ACTIVITY/BLIND_BOX/EXTERNAL_LINK',
  `jump_value` VARCHAR(500) DEFAULT '' COMMENT '跳转值（商品ID/活动ID/抽盒机ID/外部URL）',
  `status` VARCHAR(20) NOT NULL DEFAULT 'ENABLED' COMMENT '状态: ENABLED/DISABLED',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_sort` (`sort_order`),
  INDEX `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='首页轮播图';
