-- 优惠券模板表添加缺失字段
-- 请在数据库中依次执行以下语句：

-- 1. 添加 valid_days 字段（发券后有效天数）
ALTER TABLE COUPON_TEMPLATE ADD COLUMN valid_days INT NOT NULL DEFAULT 30 COMMENT '发券后有效天数';

-- 2. 添加 create_time 字段
ALTER TABLE COUPON_TEMPLATE ADD COLUMN create_time DATETIME DEFAULT CURRENT_TIMESTAMP;

-- 3. 添加 update_time 字段
ALTER TABLE COUPON_TEMPLATE ADD COLUMN update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- 用户优惠券表添加缺失字段
-- 4. 添加 create_time 字段
ALTER TABLE USER_COUPON ADD COLUMN create_time DATETIME DEFAULT CURRENT_TIMESTAMP;

-- 5. 添加 update_time 字段
ALTER TABLE USER_COUPON ADD COLUMN update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;